# SonarQube Project Information
sonar.projectKey=enterprise-three-tier
sonar.projectName=Enterprise Three Tier Application
sonar.projectVersion=1.0

# Source Code
sonar.sources=backend,frontend

# Source Encoding
sonar.sourceEncoding=UTF-8

# Exclude unnecessary files
sonar.exclusions=**/node_modules/**,**/*.sql,**/kubernetes/**